//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLaundry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineLaundryEntities : DbContext
    {
        public OnlineLaundryEntities()
            : base("name=OnlineLaundryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_confirmation> customer_confirmation { get; set; }
        public virtual DbSet<customer_subscription> customer_subscription { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<payroll> payrolls { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<service_pieces> service_pieces { get; set; }
        public virtual DbSet<service_subscription> service_subscription { get; set; }
        public virtual DbSet<service_weight> service_weight { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<working_report> working_report { get; set; }
    }
}
