//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll
    {
        public int payroll_id { get; set; }
        public int staff_id { get; set; }
        public decimal basic_salary { get; set; }
        public int working_days { get; set; }
        public Nullable<decimal> allowance { get; set; }
        public Nullable<decimal> total_salary { get; set; }
        public System.DateTime pay_date { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
