//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_weight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service_weight()
        {
            this.order_detail = new HashSet<order_detail>();
        }
    
        public int weight_id { get; set; }
        public decimal capacity { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
        public int service_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual service service { get; set; }
    }
}
