//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLaundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_detail = new HashSet<order_detail>();
        }
    
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime deliver_date { get; set; }
        public string status { get; set; }
        public Nullable<byte> shipping { get; set; }
        public decimal total_price { get; set; }
        public Nullable<int> total_pieces { get; set; }
        public Nullable<System.DateTime> last_changed { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual staff staff { get; set; }
    }
}
