//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLaundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int order_detail_id { get; set; }
        public int order_id { get; set; }
        public int service_id { get; set; }
        public Nullable<int> pieces_id { get; set; }
        public Nullable<int> weight_id { get; set; }
        public Nullable<int> subscription_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string comment { get; set; }
    
        public virtual order order { get; set; }
        public virtual service service { get; set; }
        public virtual service_pieces service_pieces { get; set; }
        public virtual service_subscription service_subscription { get; set; }
        public virtual service_weight service_weight { get; set; }
    }
}
