//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLaundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_report
    {
        public int working_report_id { get; set; }
        public int staff_id { get; set; }
        public System.DateTime current_workday { get; set; }
        public byte presence { get; set; }
        public string approval { get; set; }
        public Nullable<System.DateTime> last_changed { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
